/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "NOTE",
  "description": "用来学习记录",
  "base": "note",
  "headTags": [],
  "pages": [
    {
      "title": "Company",
      "frontmatter": {
        "title": "Company"
      },
      "regularPath": "/company/",
      "relativePath": "company/index.md",
      "key": "v-72a0bb5b",
      "path": "/company/",
      "headers": [
        {
          "level": 2,
          "title": "web-h5-health项目逻辑",
          "slug": "web-h5-health项目逻辑"
        },
        {
          "level": 2,
          "title": "web-h5-health项目目录",
          "slug": "web-h5-health项目目录"
        },
        {
          "level": 2,
          "title": "别名",
          "slug": "别名"
        },
        {
          "level": 2,
          "title": "libs/router-utils.js跳转工具使用注意事项",
          "slug": "libs-router-utils-js跳转工具使用注意事项"
        },
        {
          "level": 2,
          "title": "7.11-7.12-家庭页管理工具的迭代",
          "slug": "_7-11-7-12-家庭页管理工具的迭代"
        },
        {
          "level": 2,
          "title": "7.11-7.15-家庭页管理工具的迭代",
          "slug": "_7-11-7-15-家庭页管理工具的迭代"
        },
        {
          "level": 2,
          "title": "跳转",
          "slug": "跳转"
        },
        {
          "level": 2,
          "title": "待看",
          "slug": "待看"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "zyt的日常记录",
        "tagline": "hold",
        "features": [
          {
            "title": "是个160斤的胖子",
            "details": "是个160多斤的胖子,想要减肥,哪天你看不到这段话了,那说明我已经瘦下来了"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-26be5b6c",
      "path": "/"
    },
    {
      "title": "踩坑记录",
      "frontmatter": {
        "title": "踩坑记录"
      },
      "regularPath": "/hole/",
      "relativePath": "hole/index.md",
      "key": "v-7483d50a",
      "path": "/hole/",
      "headers": [
        {
          "level": 2,
          "title": "Cannot read properties of undefined (reading 'data')",
          "slug": "cannot-read-properties-of-undefined-reading-data"
        }
      ]
    },
    {
      "title": "Tool",
      "frontmatter": {
        "title": "Tool"
      },
      "regularPath": "/tool/",
      "relativePath": "tool/index.md",
      "key": "v-f143086a",
      "path": "/tool/",
      "headers": [
        {
          "level": 2,
          "title": "github下载并安装vue-devtools",
          "slug": "github下载并安装vue-devtools"
        },
        {
          "level": 2,
          "title": "vscode插件",
          "slug": "vscode插件"
        },
        {
          "level": 2,
          "title": "快捷键",
          "slug": "快捷键"
        },
        {
          "level": 2,
          "title": "icon-park的在线链接(Web Component)功能使用指南",
          "slug": "icon-park的在线链接-web-component-功能使用指南"
        },
        {
          "level": 2,
          "title": "Git",
          "slug": "git"
        },
        {
          "level": 3,
          "title": "Git分支管理",
          "slug": "git分支管理"
        },
        {
          "level": 3,
          "title": "Git Flow工作流",
          "slug": "git-flow工作流"
        },
        {
          "level": 3,
          "title": "常用操作",
          "slug": "常用操作"
        },
        {
          "level": 3,
          "title": "解决冲突",
          "slug": "解决冲突"
        },
        {
          "level": 3,
          "title": "git远程仓库",
          "slug": "git远程仓库"
        },
        {
          "level": 3,
          "title": "⭐公司新建分支开发功能",
          "slug": "⭐公司新建分支开发功能"
        },
        {
          "level": 3,
          "title": "⭐公司每日开发提交代码",
          "slug": "⭐公司每日开发提交代码"
        },
        {
          "level": 3,
          "title": "⭐公司提测",
          "slug": "⭐公司提测"
        },
        {
          "level": 3,
          "title": "⭐公司修改自测、测试问题时处理",
          "slug": "⭐公司修改自测、测试问题时处理"
        },
        {
          "level": 3,
          "title": "⭐公司注意事项",
          "slug": "⭐公司注意事项"
        },
        {
          "level": 3,
          "title": "本地查看不到远程新建的分支",
          "slug": "本地查看不到远程新建的分支"
        },
        {
          "level": 3,
          "title": "⭐不小心在非自己分支下进行提交的操作",
          "slug": "⭐不小心在非自己分支下进行提交的操作"
        },
        {
          "level": 3,
          "title": "git如何忽略node-module文件",
          "slug": "git如何忽略node-module文件"
        },
        {
          "level": 3,
          "title": "⭐合并发生冲突的解决方法",
          "slug": "⭐合并发生冲突的解决方法"
        },
        {
          "level": 3,
          "title": "测试回归",
          "slug": "测试回归"
        },
        {
          "level": 3,
          "title": "error: Your local changes to the following files would be overwritten by merge",
          "slug": "error-your-local-changes-to-the-following-files-would-be-overwritten-by-merge"
        },
        {
          "level": 3,
          "title": "error: src refspec master does not match any",
          "slug": "error-src-refspec-master-does-not-match-any"
        },
        {
          "level": 2,
          "title": "vscode和markdown",
          "slug": "vscode和markdown"
        },
        {
          "level": 3,
          "title": "markdown",
          "slug": "markdown"
        },
        {
          "level": 2,
          "title": "VuePress",
          "slug": "vuepress"
        },
        {
          "level": 3,
          "title": "侧边栏",
          "slug": "侧边栏"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 2,
          "title": "Vuepress部署",
          "slug": "vuepress部署"
        },
        {
          "level": 3,
          "title": "github pages",
          "slug": "github-pages"
        },
        {
          "level": 3,
          "title": "发布到github.io",
          "slug": "发布到github-io"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {
        "title": "CSS"
      },
      "regularPath": "/css/",
      "relativePath": "css/index.md",
      "key": "v-5b3a3c1b",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "固定高度导致不能下拉？",
          "slug": "固定高度导致不能下拉"
        },
        {
          "level": 2,
          "title": "8个div平均两行",
          "slug": "_8个div平均两行"
        },
        {
          "level": 2,
          "title": "样式调试技巧",
          "slug": "样式调试技巧"
        },
        {
          "level": 2,
          "title": "关于url",
          "slug": "关于url"
        },
        {
          "level": 2,
          "title": "行高line-height",
          "slug": "行高line-height"
        },
        {
          "level": 2,
          "title": "CSS rgba() 函数",
          "slug": "css-rgba-函数"
        },
        {
          "level": 2,
          "title": "纯css绘制三角形",
          "slug": "纯css绘制三角形"
        },
        {
          "level": 2,
          "title": "前端实现三角形的四种方法",
          "slug": "前端实现三角形的四种方法"
        },
        {
          "level": 2,
          "title": "flex布局",
          "slug": "flex布局"
        },
        {
          "level": 2,
          "title": "scss",
          "slug": "scss"
        },
        {
          "level": 2,
          "title": "自适应",
          "slug": "自适应"
        },
        {
          "level": 2,
          "title": "宽高内边距外边距",
          "slug": "宽高内边距外边距"
        }
      ]
    },
    {
      "title": "JS",
      "frontmatter": {
        "title": "JS"
      },
      "regularPath": "/js/",
      "relativePath": "js/index.md",
      "key": "v-06cd5229",
      "path": "/js/",
      "headers": [
        {
          "level": 2,
          "title": "布尔操作符",
          "slug": "布尔操作符"
        },
        {
          "level": 2,
          "title": "其它类型转为布尔值Boolean()函数",
          "slug": "其它类型转为布尔值boolean-函数"
        },
        {
          "level": 2,
          "title": "原生",
          "slug": "原生"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "promise",
          "slug": "promise"
        }
      ]
    },
    {
      "title": "小程序",
      "frontmatter": {
        "title": "小程序"
      },
      "regularPath": "/miniprogram/",
      "relativePath": "miniprogram/index.md",
      "key": "v-2d6086db",
      "path": "/miniprogram/",
      "headers": [
        {
          "level": 2,
          "title": "navbar去跳转新的页面",
          "slug": "navbar去跳转新的页面"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {
        "title": "Vue"
      },
      "regularPath": "/vue/",
      "relativePath": "vue/index.md",
      "key": "v-31024b3b",
      "path": "/vue/",
      "headers": [
        {
          "level": 2,
          "title": "过滤器",
          "slug": "过滤器"
        },
        {
          "level": 2,
          "title": "dayjs",
          "slug": "dayjs"
        },
        {
          "level": 2,
          "title": "this.$set是异步的",
          "slug": "this-set是异步的"
        },
        {
          "level": 2,
          "title": "computed",
          "slug": "computed"
        },
        {
          "level": 2,
          "title": "data里的数据不能互相引用",
          "slug": "data里的数据不能互相引用"
        },
        {
          "level": 2,
          "title": "data的数据是响应式的",
          "slug": "data的数据是响应式的"
        },
        {
          "level": 2,
          "title": "vm.$attrs",
          "slug": "vm-attrs"
        },
        {
          "level": 2,
          "title": "传递参数有无：的区别",
          "slug": "传递参数有无-的区别"
        },
        {
          "level": 2,
          "title": "props",
          "slug": "props"
        },
        {
          "level": 3,
          "title": "Prop 的大小写",
          "slug": "prop-的大小写"
        },
        {
          "level": 3,
          "title": "传递静态或动态 Prop",
          "slug": "传递静态或动态-prop"
        },
        {
          "level": 3,
          "title": "Prop 类型",
          "slug": "prop-类型"
        },
        {
          "level": 3,
          "title": "props为什么要默认值",
          "slug": "props为什么要默认值"
        },
        {
          "level": 2,
          "title": "动态绑定样式style",
          "slug": "动态绑定样式style"
        },
        {
          "level": 2,
          "title": "动态绑定样式class",
          "slug": "动态绑定样式class"
        },
        {
          "level": 2,
          "title": ":src",
          "slug": "src"
        },
        {
          "level": 2,
          "title": "v-for",
          "slug": "v-for"
        },
        {
          "level": 2,
          "title": "v-for和v-if不能连用",
          "slug": "v-for和v-if不能连用"
        },
        {
          "level": 2,
          "title": "template",
          "slug": "template"
        },
        {
          "level": 2,
          "title": "路由跳转",
          "slug": "路由跳转"
        },
        {
          "level": 2,
          "title": "路由跳转携带参数",
          "slug": "路由跳转携带参数"
        },
        {
          "level": 3,
          "title": "方法一 props",
          "slug": "方法一-props"
        },
        {
          "level": 2,
          "title": "拉取项目或者分支报错",
          "slug": "拉取项目或者分支报错"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/%E7%BB%84%E4%BB%B6/",
      "relativePath": "组件/index.md",
      "key": "v-b65bf158",
      "path": "/%E7%BB%84%E4%BB%B6/",
      "headers": [
        {
          "level": 2,
          "title": "title:vant组件",
          "slug": "title-vant组件"
        },
        {
          "level": 2,
          "title": "PullRefresh下拉刷新",
          "slug": "pullrefresh下拉刷新"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": "auto",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "tool",
        "link": "/tool/"
      },
      {
        "text": "company",
        "link": "/company/"
      },
      {
        "text": "vue",
        "link": "/vue/"
      },
      {
        "text": "miniprogram",
        "link": "/miniprogram/"
      },
      {
        "text": "js",
        "link": "/js/"
      },
      {
        "text": "css",
        "link": "/css/"
      },
      {
        "text": "踩坑",
        "link": "/hole/"
      }
    ]
  }
}